# Generated by Django 6.0.5 on 2026-05-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_iniciales_base', models.FloatField(default=0.0)),
                ('permitir_excedentes', models.BooleanField(default=False)),
                ('vigencia_credito_comercial', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=50)),
                ('es_administrador', models.BooleanField(default=False)),
                ('id_comercio_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros_vinculados', to='comunidad.miembrocomunidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='miembro_comunidad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_horas', models.FloatField(default=0.0)),
                ('saldo_comercial_excedente', models.FloatField(default=0.0)),
                ('estado_cuenta', models.CharField(default='ACTIVO', max_length=50)),
                ('miembro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_saldo', to='comunidad.miembrocomunidad')),
            ],
        ),
    ]
