# Generated by Django 6.0.5 on 2026-05-19 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracioncomunidad',
            options={'verbose_name': 'Configuración de la Comunidad', 'verbose_name_plural': 'Configuración de la Comunidad'},
        ),
        migrations.AlterModelOptions(
            name='cuentasaldo',
            options={'verbose_name': 'Cuenta de Saldo', 'verbose_name_plural': 'Cuentas de Saldo'},
        ),
        migrations.AlterModelOptions(
            name='miembrocomunidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Miembro de la Comunidad', 'verbose_name_plural': 'Miembros de la Comunidad'},
        ),
        migrations.RemoveField(
            model_name='cuentasaldo',
            name='saldo_comercial_excedente',
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentasaldo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cuentasaldo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembrocomunidad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='miembrocomunidad',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracioncomunidad',
            name='vigencia_credito_comercial',
            field=models.IntegerField(default=12, help_text='Vigencia del crédito comercial en meses'),
        ),
        migrations.AlterField(
            model_name='miembrocomunidad',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('PENDIENTE', 'Pendiente de validación'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=50),
        ),
    ]
