# Generated by Django 6.0.5 on 2026-05-21 19:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_remove_acuerdotrueque_creado_el_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldocomercial',
            old_name='fecha_emision',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='saldocomercial',
            name='esta_consumido',
        ),
        migrations.AddField(
            model_name='saldocomercial',
            name='tipo_movimiento',
            field=models.CharField(choices=[('EMISION', 'Emisión de vuelto'), ('PAGO', 'Pago en comercio')], default='EMISION', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo_comercial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='saldocomercial',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_saldo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saldocomercial',
            name='comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_comerciales', to=settings.AUTH_USER_MODEL),
        ),
    ]
