# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_alter_acuerdotrueque_id_alter_publicacion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioautorizado',
            name='tipo',
            field=models.CharField(choices=[('USUARIO', 'Usuario'), ('COMERCIO', 'Comercio')], default='USUARIO', max_length=10),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
