# Generated by Django 5.2.14 on 2026-06-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0008_notificacionpropuesta_match_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdotrueque',
            name='codigo_confirmacion',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
