# Generated by Django 5.2.14 on 2026-06-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0012_ensure_admin_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='es_causa_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saldocomercial',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saldocomercial',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saldocomercial',
            name='valor_producto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
