# Generated by Django 5.2.14 on 2026-06-18 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0013_publicacion_es_causa_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_fondo_comunitario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_social',
            field=models.CharField(choices=[('NINGUNO', 'Ninguno'), ('VULNERABLE', 'Vulnerable'), ('CRITICO', 'Crítico')], default='NINGUNO', max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horas_recibidas_donacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='SolicitudApoyoSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, default='', max_length=80)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('horas_recibidas', models.FloatField(default=0.0)),
                ('horas_solidarias_disponibles', models.FloatField(default=0.0)),
                ('horas_solidarias_utilizadas', models.FloatField(default=0.0)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_apoyo_social', to='comunidad.publicacion')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_apoyo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonacionHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('tipo_destino', models.CharField(choices=[('CAUSA', 'Causa'), ('FONDO', 'Fondo'), ('ASIGNACION', 'Asignación desde fondo')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprobante_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to='comunidad.solicitudapoyosocial')),
            ],
        ),
    ]
