# Generated by Django 5.2.14 on 2026-07-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0015_crear_fondo_comunitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdotrueque',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En Curso'), ('ACEPTADO', 'Aceptado'), ('FINALIZADO', 'Finalizado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='notificacionpropuesta',
            name='tipo',
            field=models.CharField(choices=[('MATCH', 'Match'), ('PROPUESTA', 'Propuesta'), ('RESENA', 'Reseña')], default='PROPUESTA', max_length=10),
        ),
    ]
