# Generated by Django 5.2.14 on 2026-07-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0016_alter_acuerdotrueque_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionpropuesta',
            name='publicacion_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='comunidad.publicacion'),
        ),
    ]
