"""
Catálogo de servicios de cartelera (subset usado para validar causas sociales).
Mantener alineado con frontend/src/data/catalogoServicios.js en estas categorías.
"""

TITULOS_POR_CATEGORIA = {
    "Cuidado de la Salud, Bienestar y Terapias": [
        "Cuidado de abuelos",
        "Acompañamiento médico",
        "Cuidado de pacientes",
        "Enfermería a domicilio",
        "Inyectología",
        "Curación de heridas",
        "Control de tensión",
        "Fisioterapia en casa",
        "Rehabilitación física",
        "Masajes relajantes",
        "Masajes terapéuticos",
        "Drenaje linfático",
        "Descarga deportiva",
        "Ajustes quiroprácticos",
        "Acupuntura",
        "Reflexología podal",
        "Terapia ocupacional",
        "Terapia de lenguaje",
        "Psicoterapia clínica",
        "Primeros auxilios online",
        "Terapia de pareja",
        "Orientación familiar",
        "Consulta de nutrición",
        "Dietas clínicas",
        "Recomposición corporal",
        "Evaluación física",
        "Entrenamiento funcional",
        "Clases de pilates",
        "Artes marciales",
        "Defensa personal",
        "Musicoterapia",
        "Arteterapia",
        "Terapia con animales",
        "Ergonomía en casa",
        "Curso de primeros auxilios",
        "Meditación guiada",
        "Higiene del sueño",
        "Limpieza facial",
        "Estética no invasiva",
        "Depilación con cera",
        "Podología clínica",
        "Rutinas de skincare",
        "Consulta de la piel",
        "Salud reproductiva",
        "Terapia de duelo",
        "Terapias holísticas",
        "Equipos ortopédicos",
        "Gimnasia mental",
        "Gimnasia prenatal",
        "Estimulación temprana",
    ],
    "Educación, Asesoría y Tutorías": [
        "Clases de matemáticas",
        "Tutoría de cálculo",
        "Clases de física",
        "Clases de química",
        "Clases de biología",
        "Enseñar programación",
        "Clases de algoritmos",
        "Inglés conversacional",
        "Preparar TOEFL",
        "Clases de francés",
        "Clases de italiano",
        "Redacción en español",
        "Apoyo escolar primaria",
        "Apoyo bachillerato",
        "Clases de historia",
        "Clases de geografía",
        "Técnicas de estudio",
        "Iniciación musical",
        "Clases de guitarra",
        "Clases de piano",
        "Clases de canto",
        "Clases de dibujo",
        "Clases de fotografía",
        "Clases de Excel",
        "Uso de IA",
        "Metodologías de software",
        "Tutoría Scrum",
        "Educación financiera",
        "Asesoría de nutrición",
        "Imagen personal",
        "Coaching de vida",
        "Orientación vocacional",
        "Preparar entrevistas",
        "Hablar en público",
        "Desenvolvimiento en cámara",
        "Clases de actuación",
        "Clases de baile",
        "Posturas de yoga",
        "Personal Trainer",
        "Clases de ajedrez",
        "Asesoría de lactancia",
        "Preparación al parto",
        "Validar ideas",
        "Planes de negocio",
        "Asesoría de importación",
        "Marketing digital",
        "Auditoría de redes",
        "Aprender costura",
        "Clases de cocina",
        "Clases de repostería",
    ],
    "Limpieza, Organización y Hogar": [
        "Limpieza profunda",
        "Limpieza básica",
        "Limpieza post-obra",
        "Limpiar oficinas",
        "Limpiar locales",
        "Limpiar vidrios",
        "Lavar alfombras",
        "Lavar muebles",
        "Lavar colchones",
        "Desinfectar ambientes",
        "Fumigar plagas",
        "Organizar armarios",
        "Organizar garajes",
        "Optimizar espacios",
        "Limpiar piscinas",
        "Químicos de piscina",
        "Jardinería básica",
        "Podar árboles",
        "Cortar césped",
        "Diseño de jardines",
        "Cuidado de plantas",
        "Sistemas de riego",
        "Quitar maleza",
        "Abonar tierra",
        "Limpiar fachadas",
        "Hidrojet de exteriores",
        "Botar escombros",
        "Clasificar reciclaje",
        "Planchado de ropa",
        "Lavandería en casa",
        "Costura básica",
        "Menús semanales",
        "Batch cooking",
        "Hacer compras",
        "Cuidar mascotas",
        "Pasear perros",
        "Adiestramiento básico",
        "Peluquería canina",
        "Cuidar gatos",
        "Limpiar peceras",
        "Plantas de interior",
        "Ayuda en mudanzas",
        "Empacar cajas",
        "Desempacar mudanzas",
        "Cuidar casas",
        "Limpiar parrilleras",
        "Limpiar canaletas",
        "Pulir pisos",
        "Encerar madera",
        "Limpiar persianas",
    ],
    "Automotriz, Transporte y Logística": [
        "Mecánica a domicilio",
        "Revisión preventiva",
        "Cambio de aceite",
        "Revisar frenos",
        "Cambiar pastillas",
        "Cambiar bujías",
        "Escaneo de motor",
        "Tren delantero",
        "Alineación y balanceo",
        "Reparar cajas",
        "Mecánica de motos",
        "Reparar bicicletas",
        "Instalar repuestos",
        "Latonería y pintura",
        "Sacar bollos",
        "Pulir carrocería",
        "Car detailing",
        "Lavar tapicería",
        "Instalar alarmas",
        "Sonido para autos",
        "Cambiar baterías",
        "Servicio de grúa",
        "Asistencia vial",
        "Carga pesada",
        "Carga ligera",
        "Fletes y mudanzas",
        "Paquetería urbana",
        "Delivery en moto",
        "Conductor de reemplazo",
        "Chófer privado",
        "Transporte escolar",
        "Transporte de personal",
        "Logística de traslados",
        "Alquiler de autos",
        "Gestoría de vehículos",
        "Revisión pre-compra",
        "Inspección mecánica",
        "Gestionar flotas",
        "Aire acondicionado auto",
        "Reparar alternadores",
        "Limpiar inyectores",
        "Rotulado de autos",
        "Reparar parabrisas",
        "Cambiar limpiaparabrisas",
        "Papel ahumado",
        "Tapizar asientos",
        "Restaurar faros",
        "Mantenimiento de escapes",
        "Traslado de mascotas",
        "Carga de maquinaria",
    ],
}
