# Generated by Django 6.0.5 on 2026-05-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acuerdotrueque',
            name='creado_el',
        ),
        migrations.RemoveField(
            model_name='acuerdotrueque',
            name='publicacion_solicitada',
        ),
        migrations.AddField(
            model_name='acuerdotrueque',
            name='emisor_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acuerdotrueque',
            name='receptor_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acuerdotrueque',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=15),
        ),
    ]
