# Generated by Django 5.2.14 on 2026-06-04 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0005_usuarioautorizado_tipo_publicacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdotrueque',
            name='actualizado_el',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='acuerdotrueque',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='acuerdotrueque',
            name='publicacion_emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_como_emisor', to='comunidad.publicacion'),
        ),
        migrations.AddField(
            model_name='acuerdotrueque',
            name='publicacion_receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_como_receptor', to='comunidad.publicacion'),
        ),
        migrations.AlterField(
            model_name='acuerdotrueque',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=15),
        ),
        migrations.CreateModel(
            name='NotificacionPropuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=300)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('LEIDA', 'Leída')], default='PENDIENTE', max_length=15)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('leida_el', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.BooleanField(default=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('publicacion_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='comunidad.publicacion')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('trueque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='comunidad.acuerdotrueque')),
            ],
            options={
                'ordering': ['-prioridad', '-creada_el'],
            },
        ),
    ]
