# Generated by Django 6.0.6 on 2026-06-09 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_acuerdotrueque_actualizado_el_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='promedio_estrellas',
        ),
        migrations.AddField(
            model_name='notificacionpropuesta',
            name='tipo',
            field=models.CharField(choices=[('MATCH', 'Match'), ('PROPUESTA', 'Propuesta')], default='PROPUESTA', max_length=10),
        ),
        migrations.AlterField(
            model_name='resena',
            name='trueque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='comunidad.acuerdotrueque'),
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.UniqueConstraint(fields=('trueque', 'calificador'), name='una_resena_por_usuario_por_trueque'),
        ),
    ]
