# Generated by Django 6.0.6 on 2026-06-11 20:42

import comunidad.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0008_notificacionpropuesta_match_detalle'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', comunidad.models.UsuarioManager()),
            ],
        ),
    ]
