# Generated by Django 5.2.14 on 2026-06-12 22:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0009_acuerdotrueque_codigo_confirmacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdoTruequeMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=15)),
                ('usuario1_aceptado', models.BooleanField(default=False)),
                ('usuario2_aceptado', models.BooleanField(default=False)),
                ('usuario3_aceptado', models.BooleanField(default=False)),
                ('par1_confirmado', models.BooleanField(default=False)),
                ('par2_confirmado', models.BooleanField(default=False)),
                ('par3_confirmado', models.BooleanField(default=False)),
                ('codigo_par1', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('codigo_par2', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('codigo_par3', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('expira_el', models.DateTimeField()),
                ('emisor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueques_multiple_emisor1', to=settings.AUTH_USER_MODEL)),
                ('emisor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueques_multiple_emisor2', to=settings.AUTH_USER_MODEL)),
                ('emisor3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueques_multiple_emisor3', to=settings.AUTH_USER_MODEL)),
                ('publicacion_emisor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_multiple_emisor1', to='comunidad.publicacion')),
                ('publicacion_emisor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_multiple_emisor2', to='comunidad.publicacion')),
                ('publicacion_emisor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_multiple_emisor3', to='comunidad.publicacion')),
                ('publicacion_receptor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_multiple_receptor1', to='comunidad.publicacion')),
                ('publicacion_receptor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_multiple_receptor2', to='comunidad.publicacion')),
                ('publicacion_receptor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_multiple_receptor3', to='comunidad.publicacion')),
                ('receptor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueques_multiple_receptor1', to=settings.AUTH_USER_MODEL)),
                ('receptor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueques_multiple_receptor2', to=settings.AUTH_USER_MODEL)),
                ('receptor3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trueques_multiple_receptor3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResenaMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(max_length=500)),
                ('calificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_multiple_recibidas', to=settings.AUTH_USER_MODEL)),
                ('calificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_multiple_emitidas', to=settings.AUTH_USER_MODEL)),
                ('trueque_multiple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_multiple', to='comunidad.acuerdotruequemultiple')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trueque_multiple', 'calificador', 'calificado'), name='una_resena_multiple_por_calificador_por_calificado')],
            },
        ),
    ]
