# Generated by Django 6.0.6 on 2026-06-14 03:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def crear_fondo_comunitario(apps, schema_editor):
    Usuario = apps.get_model("comunidad", "Usuario")
    if Usuario.objects.filter(username="fondo_comunitario").exists():
        return
    Usuario.objects.create(
        username="fondo_comunitario",
        email="fondo_comunitario@tutrueque.local",
        nombre_real="Fondo Comunitario",
        password=make_password(None),
        es_fondo_comunitario=True,
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0011_saldocomercial_valor_producto_monto_recibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_fondo_comunitario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_social',
            field=models.CharField(choices=[('NINGUNO', 'Ninguno'), ('VULNERABLE', 'Vulnerable'), ('CRITICO', 'Crítico')], default='NINGUNO', max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horas_recibidas_donacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='SolicitudApoyoSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('horas_recibidas', models.FloatField(default=0.0)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_apoyo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonacionHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('tipo_destino', models.CharField(choices=[('CAUSA', 'Causa'), ('FONDO', 'Fondo')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprobante_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to='comunidad.solicitudapoyosocial')),
            ],
        ),
        migrations.RunPython(crear_fondo_comunitario, migrations.RunPython.noop),
    ]
